### ISSUE TITLE
Gradlew compiler incorrectly parses file name in error output during 'make build'

### ISSUE THREAD

**Issue by cmcginty** [tfnico/vim-gradle#6]
When I run `:make build` after setting `:compiler gradlew` the first error tries to open a file but its blank.

When I expand the file path on the command I get:
`:proj1:compileJava/home/pcm/src/..../*.java`

It looks like a bug where the gradle Task name is getting incorrectly prefixed to the file path.

**Comment by tfnico** [comment]
As I said in another ticket, I have no idea about this, as I don't use the :compiler gradle stuff myself. 

So I'll try kicking the ball to @nathanalderson and @mearns :)

**Comment by mearns** [comment]
It's most likely because of the way vim is parsing errors output by gradle. I vaguely recall that the `errorfmt` for java, and gradle in particular, is really annoying to get working.

An `errorfmt` can probably be worked out and added to the gradle and gradlew compiler, but I'm not sure when I'll get a chance to look at this. So if anyone else can figure it out and make a pull request, that would be awesome!

**Comment by ches** [comment]
Haven't tried yet, but it appears pretty likely that the addition in #7 might solve this, but it needs to be applied to the `gradlew` compiler file too.

**Comment by mearns** [comment]
Created merge request #8 to copy the error formats from gradle compiler to gradlew, like @ches mentioned. I'm having trouble testing this, for some reason I'm not getting any error output in my quick fix window, but it's unrelated to this change (happens even without this change). So hopefully someone else can test it in my fork.

**Comment by tfnico** [comment]
@cmcginty Could you perhaps test @mearns' fork?

**Comment by cmcginty** [comment]
I tested it out and made some more changes in request #9.

**Comment by tfnico** [comment]
I'm assuming this one is safe to close now. Thanks all!
